WIP

diff --git a/redis-del b/redis-del
--- a/redis-del
+++ b/redis-del
@@ -1,4 +1,32 @@
-#!/bin/bash
+#!/bin/sh
+#
+# Usage: redis-del [-h host] [-p port] [-n db] pattern
+#
+# Matches keys with the KEYS command matching pattern
+# and deletes them from the specified Redis DB.
+ 
+set -e
+ 
+HOST="localhost"
+PORT="6379"
+DB="0"
 
-KEY=$1
-redis-cli keys "${KEY}" | awk '{print $1}' | xargs redis-cli del {} \;
+while getopts "h:p:n:" opt; do
+    case $opt in
+        h) HOST=$OPTARG;;
+        p) PORT=$OPTARG;;
+        n) DB=$OPTARG;;
+        \?) echo "invalid option: -$OPTARG" >&2; exit 1;;
+    esac
+done
+
+shift $(( $OPTIND -1 ))
+PATTERN="$@"
+
+if [ -z "$PATTERN" ]; then
+    echo "pattern required" >&2
+    exit 2
+fi
+
+redis-cli -h $HOST -p $PORT -n $DB --raw keys "$PATTERN" |  sed 's/.*/"&"/' | xargs redis-cli -h $HOST -p $PORT -n $DB del
+
